# Generated by Django 3.2.16 on 2022-10-25 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assignment1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='director',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assignment1.director'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='movie',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='assignment1.movie'),
        ),
    ]
