# Generated by Django 3.2.16 on 2022-10-26 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assignment1', '0002_auto_20221025_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cast',
            name='actor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='assignment1.actor'),
        ),
        migrations.AlterField(
            model_name='cast',
            name='movie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='assignment1.movie'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='actors',
            field=models.ManyToManyField(null=True, through='assignment1.Cast', to='assignment1.Actor'),
        ),
    ]
